// LexClear — AI for Legal Assistance & Access (PromptWars 2026 submission)
// Author: Sabarish R <sabarishr1087@gmail.com>
// Portfolio: https://sabarishr08.vercel.app | LinkedIn: https://www.linkedin.com/in/sabarishr08 | GitHub: https://github.com/SabarishR08
// Original work by the author. Please do not resubmit it as your own — see LICENSE.

import type { ContractDeadline } from "@/lib/scorecard";

/**
 * Generates an RFC-5545 compliant iCalendar (.ics) string for contract obligations.
 */
export function generateCalendarICS(documentTitle: string, deadlines: ContractDeadline[]): string {
  const now = new Date();
  const timestamp = now.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";

  // Create an upcoming placeholder date (next month 1st at 09:00 UTC)
  const targetYear = now.getFullYear();
  const targetMonth = String(now.getMonth() + 2).padStart(2, "0");
  const dateStr = `${targetYear}${targetMonth}01T090000Z`;

  const events = deadlines.map((item, idx) => {
    const uid = `lexclear-${Date.now()}-${idx}@lexclear.local`;
    const summary = `[LexClear] ${item.title} (${documentTitle})`;
    const description = `${item.actionRequired}\\n\\nTimeframe: ${item.timeframe}\\nClause Ref: ${item.clauseRef}\\n\\nNote: Generated by LexClear for information purposes only. Not legal advice.`;

    return [
      "BEGIN:VEVENT",
      `UID:${uid}`,
      `DTSTAMP:${timestamp}`,
      `DTSTART:${dateStr}`,
      `SUMMARY:${summary}`,
      `DESCRIPTION:${description}`,
      "STATUS:CONFIRMED",
      "TRANSP:TRANSPARENT",
      "END:VEVENT",
    ].join("\r\n");
  });

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//LexClear//Contract Deadline Exporter//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    ...events,
    "END:VCALENDAR",
  ].join("\r\n");
}
